### ISSUE TITLE
Building an array of heights in the profile

### ISSUE THREAD

**Issue by Rashid-S** [aatishnn/srtm-python#11]
Hi!.
In your example, you use SRTM3 cards in increments of 1 second = 100 meters. Help me write the code so that between the two geographic points you can display a profile with an array of heights?

**Comment by aatishnn** [comment]
This is similar to what you are looking for: https://gis.stackexchange.com/questions/157693/getting-all-vertex-lat-long-coordinates-every-1-meter-between-two-known-points

In summary: get a list of points between two geo points and plot the values obtained from this library for each of those points.

**Comment by Rashid-S** [comment]
Aatishnn, really seems the right path you pointed out. Thank you very much.

**Comment by aatishnn** [comment]
@Rashid-S when you do that, if possible, please share the code here.
